/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain.tables;


import by.gsu.domain.DefaultSchema;
import by.gsu.domain.Indexes;
import by.gsu.domain.Keys;
import by.gsu.domain.tables.records.TemplateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Template extends TableImpl<TemplateRecord> {

    private static final long serialVersionUID = 1740665750;

    /**
     * The reference instance of <code>template</code>
     */
    public static final Template TEMPLATE = new Template();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TemplateRecord> getRecordType() {
        return TemplateRecord.class;
    }

    /**
     * The column <code>template.id</code>.
     */
    public final TableField<TemplateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>template.value</code>.
     */
    public final TableField<TemplateRecord, byte[]> VALUE = createField("value", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>template.name</code>.
     */
    public final TableField<TemplateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>template</code> table reference
     */
    public Template() {
        this(DSL.name("template"), null);
    }

    /**
     * Create an aliased <code>template</code> table reference
     */
    public Template(String alias) {
        this(DSL.name(alias), TEMPLATE);
    }

    /**
     * Create an aliased <code>template</code> table reference
     */
    public Template(Name alias) {
        this(alias, TEMPLATE);
    }

    private Template(Name alias, Table<TemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private Template(Name alias, Table<TemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Template(Table<O> child, ForeignKey<O, TemplateRecord> key) {
        super(child, key, TEMPLATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEMPLATE_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TemplateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TemplateRecord> getPrimaryKey() {
        return Keys.PK_TEMPLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TemplateRecord>> getKeys() {
        return Arrays.<UniqueKey<TemplateRecord>>asList(Keys.PK_TEMPLATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Template as(String alias) {
        return new Template(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Template as(Name alias) {
        return new Template(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Template rename(String name) {
        return new Template(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Template rename(Name name) {
        return new Template(name, null);
    }
}
