/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain.tables;


import by.gsu.domain.DefaultSchema;
import by.gsu.domain.Indexes;
import by.gsu.domain.Keys;
import by.gsu.domain.tables.records.UserEventRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEvent extends TableImpl<UserEventRecord> {

    private static final long serialVersionUID = -1930863488;

    /**
     * The reference instance of <code>user_event</code>
     */
    public static final UserEvent USER_EVENT = new UserEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserEventRecord> getRecordType() {
        return UserEventRecord.class;
    }

    /**
     * The column <code>user_event.id</code>.
     */
    public final TableField<UserEventRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>user_event.userId</code>.
     */
    public final TableField<UserEventRecord, Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_event.eventId</code>.
     */
    public final TableField<UserEventRecord, Integer> EVENTID = createField("eventId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>user_event</code> table reference
     */
    public UserEvent() {
        this(DSL.name("user_event"), null);
    }

    /**
     * Create an aliased <code>user_event</code> table reference
     */
    public UserEvent(String alias) {
        this(DSL.name(alias), USER_EVENT);
    }

    /**
     * Create an aliased <code>user_event</code> table reference
     */
    public UserEvent(Name alias) {
        this(alias, USER_EVENT);
    }

    private UserEvent(Name alias, Table<UserEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserEvent(Name alias, Table<UserEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserEvent(Table<O> child, ForeignKey<O, UserEventRecord> key) {
        super(child, key, USER_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_EVENT_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserEventRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserEventRecord> getPrimaryKey() {
        return Keys.PK_USER_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserEventRecord>> getKeys() {
        return Arrays.<UniqueKey<UserEventRecord>>asList(Keys.PK_USER_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserEventRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserEventRecord, ?>>asList(Keys.FK_USER_EVENT_USER_1, Keys.FK_USER_EVENT_EVENT_1);
    }

    public User user() {
        return new User(this, Keys.FK_USER_EVENT_USER_1);
    }

    public Event event() {
        return new Event(this, Keys.FK_USER_EVENT_EVENT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEvent as(String alias) {
        return new UserEvent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEvent as(Name alias) {
        return new UserEvent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserEvent rename(String name) {
        return new UserEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserEvent rename(Name name) {
        return new UserEvent(name, null);
    }
}
