/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain;


import by.gsu.domain.tables.Event;
import by.gsu.domain.tables.Template;
import by.gsu.domain.tables.User;
import by.gsu.domain.tables.UserEvent;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENTS_ID_UINDEX = Indexes0.EVENTS_ID_UINDEX;
    public static final Index TEMPLATE_ID_UINDEX = Indexes0.TEMPLATE_ID_UINDEX;
    public static final Index USER_ID_UINDEX = Indexes0.USER_ID_UINDEX;
    public static final Index USER_EVENT_ID_UINDEX = Indexes0.USER_EVENT_ID_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EVENTS_ID_UINDEX = Internal.createIndex("events_id_uindex", Event.EVENT, new OrderField[] { Event.EVENT.ID }, true);
        public static Index TEMPLATE_ID_UINDEX = Internal.createIndex("template_id_uindex", Template.TEMPLATE, new OrderField[] { Template.TEMPLATE.ID }, true);
        public static Index USER_ID_UINDEX = Internal.createIndex("user_id_uindex", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_EVENT_ID_UINDEX = Internal.createIndex("user_event_id_uindex", UserEvent.USER_EVENT, new OrderField[] { UserEvent.USER_EVENT.ID }, true);
    }
}
