/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain;


import by.gsu.domain.tables.Event;
import by.gsu.domain.tables.Template;
import by.gsu.domain.tables.User;
import by.gsu.domain.tables.UserEvent;
import by.gsu.domain.tables.records.EventRecord;
import by.gsu.domain.tables.records.TemplateRecord;
import by.gsu.domain.tables.records.UserEventRecord;
import by.gsu.domain.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EventRecord, Integer> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
    public static final Identity<TemplateRecord, Integer> IDENTITY_TEMPLATE = Identities0.IDENTITY_TEMPLATE;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<UserEventRecord, Integer> IDENTITY_USER_EVENT = Identities0.IDENTITY_USER_EVENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> PK_EVENT = UniqueKeys0.PK_EVENT;
    public static final UniqueKey<TemplateRecord> PK_TEMPLATE = UniqueKeys0.PK_TEMPLATE;
    public static final UniqueKey<UserRecord> PK_USER = UniqueKeys0.PK_USER;
    public static final UniqueKey<UserEventRecord> PK_USER_EVENT = UniqueKeys0.PK_USER_EVENT;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EventRecord, TemplateRecord> FK_EVENT_TEMPLATE_1 = ForeignKeys0.FK_EVENT_TEMPLATE_1;
    public static final ForeignKey<UserEventRecord, UserRecord> FK_USER_EVENT_USER_1 = ForeignKeys0.FK_USER_EVENT_USER_1;
    public static final ForeignKey<UserEventRecord, EventRecord> FK_USER_EVENT_EVENT_1 = ForeignKeys0.FK_USER_EVENT_EVENT_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EventRecord, Integer> IDENTITY_EVENT = Internal.createIdentity(Event.EVENT, Event.EVENT.ID);
        public static Identity<TemplateRecord, Integer> IDENTITY_TEMPLATE = Internal.createIdentity(Template.TEMPLATE, Template.TEMPLATE.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
        public static Identity<UserEventRecord, Integer> IDENTITY_USER_EVENT = Internal.createIdentity(UserEvent.USER_EVENT, UserEvent.USER_EVENT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EventRecord> PK_EVENT = Internal.createUniqueKey(Event.EVENT, "pk_event", Event.EVENT.ID);
        public static final UniqueKey<TemplateRecord> PK_TEMPLATE = Internal.createUniqueKey(Template.TEMPLATE, "pk_template", Template.TEMPLATE.ID);
        public static final UniqueKey<UserRecord> PK_USER = Internal.createUniqueKey(User.USER, "pk_user", User.USER.ID);
        public static final UniqueKey<UserEventRecord> PK_USER_EVENT = Internal.createUniqueKey(UserEvent.USER_EVENT, "pk_user_event", UserEvent.USER_EVENT.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EventRecord, TemplateRecord> FK_EVENT_TEMPLATE_1 = Internal.createForeignKey(by.gsu.domain.Keys.PK_TEMPLATE, Event.EVENT, "fk_event_template_1", Event.EVENT.TEMPLATEID);
        public static final ForeignKey<UserEventRecord, UserRecord> FK_USER_EVENT_USER_1 = Internal.createForeignKey(by.gsu.domain.Keys.PK_USER, UserEvent.USER_EVENT, "fk_user_event_user_1", UserEvent.USER_EVENT.USERID);
        public static final ForeignKey<UserEventRecord, EventRecord> FK_USER_EVENT_EVENT_1 = Internal.createForeignKey(by.gsu.domain.Keys.PK_EVENT, UserEvent.USER_EVENT, "fk_user_event_event_1", UserEvent.USER_EVENT.EVENTID);
    }
}
