/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain;


import by.gsu.domain.tables.Event;
import by.gsu.domain.tables.Person;
import by.gsu.domain.tables.PersonDgTmp;
import by.gsu.domain.tables.records.EventRecord;
import by.gsu.domain.tables.records.PersonDgTmpRecord;
import by.gsu.domain.tables.records.PersonRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EventRecord, Integer> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
    public static final Identity<PersonRecord, Integer> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
    public static final Identity<PersonDgTmpRecord, Integer> IDENTITY_PERSON_DG_TMP = Identities0.IDENTITY_PERSON_DG_TMP;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> PK_EVENT = UniqueKeys0.PK_EVENT;
    public static final UniqueKey<PersonRecord> PK_PERSON = UniqueKeys0.PK_PERSON;
    public static final UniqueKey<PersonDgTmpRecord> PK_PERSON_DG_TMP = UniqueKeys0.PK_PERSON_DG_TMP;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EventRecord, Integer> IDENTITY_EVENT = Internal.createIdentity(Event.EVENT, Event.EVENT.ID);
        public static Identity<PersonRecord, Integer> IDENTITY_PERSON = Internal.createIdentity(Person.PERSON, Person.PERSON.ID);
        public static Identity<PersonDgTmpRecord, Integer> IDENTITY_PERSON_DG_TMP = Internal.createIdentity(PersonDgTmp.PERSON_DG_TMP, PersonDgTmp.PERSON_DG_TMP.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EventRecord> PK_EVENT = Internal.createUniqueKey(Event.EVENT, "pk_event", Event.EVENT.ID);
        public static final UniqueKey<PersonRecord> PK_PERSON = Internal.createUniqueKey(Person.PERSON, "pk_person", Person.PERSON.ID);
        public static final UniqueKey<PersonDgTmpRecord> PK_PERSON_DG_TMP = Internal.createUniqueKey(PersonDgTmp.PERSON_DG_TMP, "pk_person_dg_tmp", PersonDgTmp.PERSON_DG_TMP.ID);
    }
}
