/*
 * This file is generated by jOOQ.
 */
package by.gsu.domain;


import by.gsu.domain.tables.Event;
import by.gsu.domain.tables.Person;
import by.gsu.domain.tables.PersonEvent;
import by.gsu.domain.tables.SqliteSequence;
import by.gsu.domain.tables.Template;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>event</code>.
     */
    public static final Event EVENT = by.gsu.domain.tables.Event.EVENT;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = by.gsu.domain.tables.Person.PERSON;

    /**
     * The table <code>person_event</code>.
     */
    public static final PersonEvent PERSON_EVENT = by.gsu.domain.tables.PersonEvent.PERSON_EVENT;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = by.gsu.domain.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>template</code>.
     */
    public static final Template TEMPLATE = by.gsu.domain.tables.Template.TEMPLATE;
}
